run:
  # timeout for analysis
  deadline: 10m

linters-settings:
  govet:
    # Don't report about shadowed variables
    check-shadowing: false
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  exhaustive:
    # check switch statements in generated files also
    check-generated: false

    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: true
  revive:
    rules:
      - name: var-naming
        disabled: true
  whitespace:
    # Enforces newlines (or comments) after every multi-line if statement.
    # Default: false
    multi-if: true

    # Enforces newlines (or comments) after every multi-line function signature.
    # Default: false
    multi-func: true

linters:
  enable:
    - exhaustive
    - exportloopref
    - gci
    - gofmt
    - misspell
    - nilerr
    - nlreturn
    - revive
    - unconvert
    - unparam
    - wastedassign
    - execinquery
    - nonamedreturns
    - nosprintfhostport
    - containedctx
    - errchkjson
    - contextcheck
    - errname
    - wastedassign
    - nilerr
    - gosec    
    - govet
    - whitespace

issues:
   exclude-rules:
    # Exclude gosec from running for tests so that tests with weak randomness
    # (math/rand) will pass the linter.
    - path: _test\.go
      linters:
        - gosec
