name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: golang:1.18

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: bottle_test
          POSTGRES_USER: bottle_test
          POSTGRES_PASSWORD: bottle_test

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run tests
        # Runs a script that creates a PostgreSQL client,
        # populates the client with data, and retrieves data
        run: go test -cover ./...
        env:
          LNMUX_TEST_DB_DSN: "postgres://bottle_test:bottle_test@postgres/bottle_test?sslmode=disable"
